### ISSUE TITLE
Serialized Property hangs Debugger and Unity

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#125]
Serialized Property have drop down and even in Mono need time to fill it.
Here says Collecting data... and hangs forever.

**Comment by VISTALL** [comment]
Can you attach example ? (with source code and screenshot, gif if you can). Looks like some bug in debugger.

Thanks

**Comment by winxalex** [comment]
ull
mono.debugger.InvalidObjectException
	at mono.debugger.JDWPException.asUncheckedException(JDWPException.java:54)
	at mono.debugger.ObjectValueMirror.type(ObjectValueMirror.java:54)
	at mono.debugger.ArrayValueMirror.type(ArrayValueMirror.java:84)
	at consulo.dotnet.mono.debugger.proxy.MonoValueProxyBase.getType(MonoValueProxyBase.java:62)
	at consulo.dotnet.debugger.nodes.DotNetValuePresentation$1.visitArrayValue(DotNetValuePresentation.java:102)
	at consulo.dotnet.mono.debugger.proxy.MonoArrayValueProxy.accept(MonoArrayValueProxy.java:40)
	at consulo.dotnet.debugger.nodes.DotNetValuePresentation.getType(DotNetValuePresentation.java:72)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.buildText(XValueNodeImpl.java:212)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.buildText(XValueNodeImpl.java:205)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.updateText(XValueNodeImpl.java:194)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.applyPresentation(XValueNodeImpl.java:114)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodePresentationConfigurator.doSetPresentation(XValueNodePresentationConfigurator.java:95)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodePresentationConfigurator.setPresentation(XValueNodePresentationConfigurator.java:59)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.setPresentation(XValueNodeImpl.java:99)
	at consulo.dotnet.debugger.nodes.DotNetAbstractVariableValueNode.computePresentation(DotNetAbstractVariableValueNode.java:291)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:71)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.lambda$addChildren$0(XValueContainerNode.java:98)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:83)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:80)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:368)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by VISTALL** [comment]
Hi. Added check

Thanks

**Comment by VISTALL** [comment]
Fixed this problem
