### ISSUE TITLE
Editor attach and MacOS

### ISSUE THREAD

**Issue by VISTALL** [consulo/consulo-unity3d#13]
Hm. When i tried to attach i get exception:

``` csharp
null
java.lang.NullPointerException
    at org.mustbe.consulo.unity3d.run.Unity3dAttachRunner$1$1.connectionSuccess(Unity3dAttachRunner.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy90.connectionSuccess(Unknown Source)
    at org.mustbe.consulo.dotnet.debugger.DotNetDebugThread.run(DotNetDebugThread.java:184)

```

**Comment by VISTALL** [comment]
And debugger cant attach. Wtf?)

**Comment by VISTALL** [comment]
Strange - socket freezed while attach

**Comment by jharrison63** [comment]
Same here , when trying to attach before I launch the game it gets frozen. Also, when I attempt to step through code I get the exception:

```
Only one step request allowed per thread: Only one step request allowed per thread
mono.debugger.request.DuplicateRequestException: Only one step request allowed per thread
    at mono.debugger.request.StepRequest.<init>(StepRequest.java:91)
    at mono.debugger.EventRequestManagerImpl.createStepRequest(EventRequestManagerImpl.java:76)
    at org.mustbe.consulo.dotnet.debugger.DotNetDebugProcess$3.process(DotNetDebugProcess.java:256)
    at org.mustbe.consulo.dotnet.debugger.DotNetDebugProcess$3.process(DotNetDebugProcess.java:251)
    at org.mustbe.consulo.dotnet.debugger.DotNetDebugThread.processCommands(DotNetDebugThread.java:344)
    at org.mustbe.consulo.dotnet.debugger.DotNetDebugThread.run(DotNetDebugThread.java:227)
```

However, if I don't step and just attach where I want to debug that spot it works. Great improvements and better then MonoDevelop already! :-D

**Comment by VISTALL** [comment]
About that trace - sometimes i reproduced it. It related to Mono .NET debugger (it already requested review - but hard for me find time)

**Comment by VISTALL** [comment]
Thanks anyway

**Comment by VISTALL** [comment]
About 'Step Requst'. I pushed possible fix for it 

https://github.com/consulo/consulo-dotnet/commit/8fdac6062186d77d278771bf190051c1ef3be81f

After few hours -u can update plugin, and test

Thanks!

**Comment by jharrison63** [comment]
I'll try this soon, thanks for getting this in so fast!

**Comment by VISTALL** [comment]
Any news?

**Comment by jharrison63** [comment]
I will need to use it for a couple days more but so far I have not been able to reproduce that issue anymore.

**Comment by VISTALL** [comment]
Nice

**Comment by VISTALL** [comment]
Feedback about unity debugger(or consulo or c# impl) will be helpfull
