### ISSUE TITLE
The type or namespace name 'TMPro' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by brogan89** [consulo/consulo-unity3d#167]
Hi, after updating to Nightly builds I am having this error with my project. This seems more like a Unity package issue so I thought I just reimport the package, but the Package Manager is missing in the Windows tab. So then I tried the following steps:

- Reimport all assets (issue remains)
- Delete Library folder, *.sln *.csproj files (issue remains)
- updated Unity version to 2018.3.3f1 (issue remains)
- created new project in 2018.3.1f1 (no issues everything works as expected)

So then I had a look at the differences between to two projects and in the `Assembly-CSharp.csproj` I see the new project has references to TMPro and Package manager.

```
 <Reference Include="Unity.TextMeshPro.Editor">
 <HintPath>/home/brogan/Unity/New Unity Project/Library/ScriptAssemblies/Unity.TextMeshPro.Editor.dll</HintPath>
 </Reference>
 <Reference Include="Unity.PackageManagerUI.Editor">
 <HintPath>/home/brogan/Unity/New Unity Project/Library/ScriptAssemblies/Unity.PackageManagerUI.Editor.dll</HintPath>
 </Reference>
 <Reference Include="Unity.TextMeshPro">
 <HintPath>/home/brogan/Unity/New Unity Project/Library/ScriptAssemblies/Unity.TextMeshPro.dll</HintPath>
 </Reference>
```
but my broken project does not have these references.

These things are locally generated so now I'm wondering is there any caching that Consulo does that I can clear out so my project can be rebuilt properly again?

**Comment by brogan89** [comment]
Ok on further investigation I removed the `.consulo` folder and the `UnityEditorConsuloPlugin2017.2.dll` file along with `Library` folder, `*.sln` `*.csproj`. Then I opened Unity project and then Consulo. Consulo then prompt me to update Unity project and rebuild project. Clicked both of those. Then back into the `.dll` plugin added itself to the Unity project in `/Assets/Editor/Plugins` folder. I originally put it in manually under `/Assets/Plugins/Editor` didn't think that would make a difference but im rolling with it for now.

So not quite sure what happened there. But it is all working as expected now. One guess is something got mixed up in the `modules.xml` file in `/.consulo` or/and the `UnityEditorConsuloPlugin2017` plugin was mixed up. 

This brings up a couple questions:
1. what does the `UnityEditorConsuloPlugin2017` plugin actually do?
2. and why can't you have it as a `.unitypackage` with source code in the editor? That way it might be easier to pin point exactly what happened in that plug. -- I know there is source code on github, but Unity might've been able point to a line in the code.

**Comment by VISTALL** [comment]
Good morning :)

I will give answer for simple questions first

**VS files**
Consulo don't use VS project files, due their limitation - that why there no sense of them (consulo analyze unity project by self implementation).
That why - need **always** call **Re-import Unity project** after each external project change (it's pain i known - but there no Unity api for handle it from Unity)

**UnityEditorConsuloPlugin**
It's a hacky library, which provide **REST API** for UnityEditor - and webclient for sending REST requests to Consulo

For example, on each Reimport Consulo request preprocessor variables from Unity. This code you can found here (https://github.com/consulo/UnityEditorConsuloPlugin/blob/master/Sources/HTTPServer.cs#L107)

Also - it's help Consulo open Unity correctly. For example - if you not imported Unity project, but opened Consulo - it will import it, and open selected file (or just open project if exists)

**Comment by VISTALL** [comment]
Package manager.

As you found - there some different between  2018.3.3f vs 2018.3.1f1.

For 2018.3.3f Consulo search package sources in project files

![](https://klikr.org/bdfe67c822cae72908a4b70b402c.png)

For lower versions - it search packages in user-home files (hello unity devs).

Can you check have you correct Package directory in project files?

**Comment by VISTALL** [comment]
As workaround you can add target library to correct module(project in VS naming)

here
![](https://klikr.org/ba2fd61c4c006558ed6c7e15fba3.png)

But it will reset after each reimport - that why need find this bug.

Can you say your OS?

**Comment by brogan89** [comment]
I have updated to Unity 2018.3.3f1 now. My project window in Consulo doesn't actually show the Library folder. Instead i have a folder called "External Libraries" and it is within that. 

![image](https://user-images.githubusercontent.com/8637789/51793042-5c564900-221f-11e9-8552-c978dae6e486.png)

I'm using Consulo on Linux most at the moment. Pop!_OS. but I also use Windows. The issue I had was also on Windows but I can't confirm the Library Project file structure at the moment.

**Comment by VISTALL** [comment]
'External Libraries' is virtual node which show external libraries (.net libraries, etc)

Library directory - is Unity cache directory it's must exists.

Can you open project in Unity
> updated Unity version to 2018.3.3f1 (issue remains)

it will refresh project files and compile it.

Then open it in Consulo - and invoke **Re-import Unity Project**

and show me

$PROJECT_ROOT$\Library\PackageCache

and what path Consulo resolving in **External Libraries > com.unity.textmeshpro@1.x.x**

Thanks

**Comment by brogan89** [comment]
hi @VISTALL I have followed your steps but I don't see Library fold in Consulo (as below) 
![consulo project](https://user-images.githubusercontent.com/8637789/51808215-e4a71d80-22f5-11e9-8b91-fd6182fb7eb1.png)
but it is still present in project root, as it should always exist. and the version of TMPro is 1.3.0 at bottom of picture below. 
![library](https://user-images.githubusercontent.com/8637789/51808225-0dc7ae00-22f6-11e9-921b-de6ec81daae5.png)

Hope this helps.

**Comment by brogan89** [comment]
I just tried same thing on windows PC and same thing as Linux. Other than when I clicked `Re-import Unity Project` i got this message in bottom right 
![image](https://user-images.githubusercontent.com/8637789/51808474-2e453780-22f9-11e9-9476-fefb50eaaae1.png)

Then when I click on script to from Unity to open in Consulo I get error message:
```
unable to get stub builder for consulo.unity3d.Unity3dMetaFileType@57036063, path = C:/Users/brogan/Documents/Unity/out-of-sight/Assets/_Scripts/Helpers/DynamicSortingGroup.cs.meta, stubBindingRoot = YAMLFileImpl, languages = [yaml], fileTypes = [META], files = [YAMLFileImpl], roots = []
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:122)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:82)
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:53)
	at com.intellij.psi.stubs.StubIndexImpl$2.process(StubIndexImpl.java:336)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:651)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.perform(StubIndexImpl.java:639)
	at com.intellij.util.indexing.ValueContainer.forEach(ValueContainer.java:62)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:362)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:327)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:316)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:80)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:99)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:299)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:38)
	at consulo.unity3d.unityscript.lang.impl.UnityScriptRootNamespaceAsElement$1.compute(UnityScriptRootNamespaceAsElement.java:60)
	at consulo.dotnet.lang.psi.impl.DotNetNamespaceCacheManager.computeElements(DotNetNamespaceCacheManager.java:373)
	at consulo.unity3d.unityscript.lang.impl.UnityScriptRootNamespaceAsElement.getOnlyElements(UnityScriptRootNamespaceAsElement.java:87)
	at consulo.dotnet.lang.psi.impl.BaseDotNetNamespaceAsElement.getChildren(BaseDotNetNamespaceAsElement.java:162)
	at consulo.dotnet.lang.psi.impl.BaseDotNetNamespaceAsElement.getChildren(BaseDotNetNamespaceAsElement.java:139)
	at consulo.dotnet.lang.psi.impl.BaseDotNetNamespaceAsElement.findChildren(BaseDotNetNamespaceAsElement.java:118)
	at consulo.dotnet.lang.psi.impl.CompositeDotNetNamespaceAsElement.findChildren(CompositeDotNetNamespaceAsElement.java:89)
	at consulo.csharp.lang.psi.impl.resolve.CSharpNamespaceResolveContext.findByName(CSharpNamespaceResolveContext.java:201)
	at consulo.csharp.lang.psi.resolve.MemberByNameSelector.doSelectElement(MemberByNameSelector.java:52)
	at consulo.csharp.lang.psi.impl.source.resolve.MemberResolveScopeProcessor.execute(MemberResolveScopeProcessor.java:104)
	at consulo.csharp.lang.psi.impl.source.resolve.util.CSharpResolveUtil.walkUsing(CSharpResolveUtil.java:174)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.processAnyMember(CSharpReferenceExpressionImplUtil.java:924)
	at consulo.csharp.lang.psi.impl.source.resolve.handlers.TypeLikeKindProcessor.process(TypeLikeKindProcessor.java:42)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.collectResults(CSharpReferenceExpressionImplUtil.java:672)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:652)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:596)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolveImpl(CSharpReferenceExpressionImplUtil.java:554)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolveImpl(CSharpStubReferenceExpressionImpl.java:150)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:103)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:94)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:148)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolve(CSharpReferenceExpressionImplUtil.java:218)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:142)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:134)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.resolve(CSharpStubReferenceExpressionImpl.java:166)
	at consulo.csharp.lang.psi.impl.source.resolve.type.CSharpUserTypeRef.resolveResult(CSharpUserTypeRef.java:195)
	at consulo.dotnet.resolve.DotNetTypeRefWithCachedResult.resolve(DotNetTypeRefWithCachedResult.java:69)
	at consulo.csharp.lang.psi.impl.source.resolve.type.wrapper.GenericUnwrapTool.exchangeTypeRef(GenericUnwrapTool.java:339)
	at consulo.csharp.lang.psi.impl.source.resolve.type.wrapper.GenericUnwrapTool.exchangeTypeRef(GenericUnwrapTool.java:282)
	at consulo.csharp.lang.psi.impl.resolve.CSharpTypeResolveContext.lambda$getExtendTypeRefs$0(CSharpTypeResolveContext.java:70)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:110)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at consulo.csharp.lang.psi.impl.resolve.CSharpTypeResolveContext.getExtendTypeRefs(CSharpTypeResolveContext.java:70)
	at consulo.csharp.lang.psi.impl.resolve.CSharpBaseResolveContext.getSuperContextImpl(CSharpBaseResolveContext.java:159)
	at consulo.csharp.lang.psi.impl.resolve.CSharpBaseResolveContext.getSuperContext(CSharpBaseResolveContext.java:152)
	at consulo.csharp.lang.psi.impl.resolve.CSharpBaseResolveContext.findByName(CSharpBaseResolveContext.java:374)
	at consulo.csharp.lang.psi.resolve.AttributeByNameSelector.doSelectElement(AttributeByNameSelector.java:71)
	at consulo.csharp.lang.psi.impl.source.resolve.MemberResolveScopeProcessor.execute(MemberResolveScopeProcessor.java:104)
	at consulo.csharp.lang.psi.impl.source.resolve.util.CSharpResolveUtil.walkChildren(CSharpResolveUtil.java:339)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.processAnyMember(CSharpReferenceExpressionImplUtil.java:912)
	at consulo.csharp.lang.psi.impl.source.resolve.handlers.TypeLikeKindProcessor.process(TypeLikeKindProcessor.java:42)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.collectResults(CSharpReferenceExpressionImplUtil.java:672)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:652)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:596)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolveImpl(CSharpReferenceExpressionImplUtil.java:554)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolveImpl(CSharpStubReferenceExpressionImpl.java:150)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.resolveByTypeKind(CSharpReferenceExpressionImplUtil.java:542)
	at consulo.csharp.lang.psi.impl.source.CSharpStubAttributeImpl.resolveToType(CSharpStubAttributeImpl.java:70)
	at consulo.csharp.lang.psi.impl.source.CSharpStubAttributeImpl.toTypeRef(CSharpStubAttributeImpl.java:82)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.processAnyMember(CSharpReferenceExpressionImplUtil.java:748)
	at consulo.csharp.lang.psi.impl.source.resolve.handlers.MethodLikeKindProcessor.process(MethodLikeKindProcessor.java:72)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.collectResults(CSharpReferenceExpressionImplUtil.java:672)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:652)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:596)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolveImpl(CSharpReferenceExpressionImplUtil.java:554)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolveImpl(CSharpStubReferenceExpressionImpl.java:150)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:103)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:94)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:148)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:171)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:163)
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolve(CSharpReferenceExpressionImplUtil.java:218)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:142)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:134)
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.resolve(CSharpStubReferenceExpressionImpl.java:166)
	at consulo.csharp.lang.psi.impl.source.CSharpStubAttributeImpl.resolveToCallable(CSharpStubAttributeImpl.java:123)
	at consulo.dotnet.lang.MultiHostInjectorByAttribute.injectLanguages(MultiHostInjectorByAttribute.java:57)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:498)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:267)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:139)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$2(InjectedGeneralHighlightingPass.java:188)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:135)
	at consulo.application.impl.BaseApplication.tryRunReadAction(BaseApplication.java:547)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:100)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:144)
	at consulo.application.impl.BaseApplication.executeByImpatientReader(BaseApplication.java:597)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:67)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.getInjectedPsiFiles(InjectedGeneralHighlightingPass.java:184)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.collectInformationWithProgress(InjectedGeneralHighlightingPass.java:89)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:87)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:74)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:419)
	at consulo.application.impl.BaseApplication.tryRunReadAction(BaseApplication.java:552)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:100)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:411)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:387)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:144)
	at consulo.application.impl.BaseApplication.executeByImpatientReader(BaseApplication.java:597)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:385)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:163)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Good thing is I'm not getting that error anymore. I actually can't remember what we did. Was it simply just updating to Unity 2018.3.3?

**Comment by VISTALL** [comment]
Hello. I forgot about **Library**, this directory is excluded from project (searching, indexing, etc). 

For showing it in project view (click on Gear at Project toolwindow - Show Excluded Files)

In last project (which you show) - TMPro problem exists? 

Can you expand this node - and check package source? 

![](https://user-images.githubusercontent.com/8637789/51793042-5c564900-221f-11e9-8552-c978dae6e486.png)

Also can you say in what file you have problem? (file path is important due Editor code compiled in another library, and have another dependencies)

Thanks

**Comment by brogan89** [comment]
ah yeap. The "External Libraries" package is the exact same as the "Library" folder package. Both same directory. 

I do not have TMPro packages missing anymore since https://github.com/consulo/consulo-unity3d/issues/167#issuecomment-457867918 :smile: I am thinking this is solved now but I can't figure out how it got solved. I think just updating to 2018.3.3 is all it needed because you said Consulo looks for package in different directory for that Unity version?

**Comment by VISTALL** [comment]
Idk :D I do nothing. I don't known that bug u catch.

**Comment by brogan89** [comment]
yea. im pretty confused now too haha. I will try to reproduce tonight after work.
