### ISSUE TITLE
Autocomplete doesn't work with Unity LTS 2020.3

### ISSUE THREAD

**Issue by Zeon8** [consulo/consulo-unity3d#200]
When I open projects with Unity LTS 2020.3 Consulo allways shows "Analyzing..." and autocomplete doesn't work.
Here is error in consulo.log:
```
[ 389377]  ERROR - stubs.StubProcessingHelperBase - unable to get stub builder for consulo.unity3d.Unity3dMetaFileType@100a1483, path = E:/Work/Unity Projects/MirrorTest/Library/PackageCache/com.unity.timeline@1.4.6/Editor/Window/TimelineWindowTimeControl.cs.meta, stubBindingRoot = YAMLFileImpl, languages = [yaml], fileTypes = [META], files = [YAMLFileImpl], roots = [] 
java.lang.Throwable: null
	at consulo.logging.Logger.error(Logger.java:94) ~[Logger.class:?]
	at com.intellij.psi.stubs.StubProcessingHelperBase.handleNonPsiStubs(StubProcessingHelperBase.java:109) ~[CustomSyntaxTableFileType.class:?]
	at com.intellij.psi.stubs.StubProcessingHelperBase.processStubsInFile(StubProcessingHelperBase.java:63) ~[CustomSyntaxTableFileType.class:?]
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:389) ~[FileBasedIndexImpl.class:?]
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:49) ~[FileBasedIndex.class:?]
	at consulo.dotnet.resolve.impl.IndexBasedDotNetPsiSearcher.isFoundAnyOneElement(IndexBasedDotNetPsiSearcher.java:85) ~[?:?]
	at consulo.dotnet.resolve.impl.IndexBasedDotNetPsiSearcher.findNamespaceImpl(IndexBasedDotNetPsiSearcher.java:72) ~[?:?]
	at consulo.dotnet.resolve.impl.IndexBasedDotNetPsiSearcher.findNamespace(IndexBasedDotNetPsiSearcher.java:61) ~[?:?]
	at consulo.dotnet.lang.psi.impl.DotNetNamespaceCacheManager.computeNamespaceImpl(DotNetNamespaceCacheManager.java:355) ~[?:?]
	at consulo.dotnet.lang.psi.impl.DotNetNamespaceCacheManager.computeNamespace(DotNetNamespaceCacheManager.java:332) ~[?:?]
	at consulo.dotnet.resolve.impl.DotNetPsiSearcherImpl.findNamespace(DotNetPsiSearcherImpl.java:59) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpUsingNamespaceStatementImpl.resolveInner(CSharpUsingNamespaceStatementImpl.java:106) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpUsingNamespaceStatementImpl.lambda$resolve$0(CSharpUsingNamespaceStatementImpl.java:80) ~[?:?]
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:162) ~[ApplicationProperties.class:?]
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54) ~[PluginManagerCore.class:?]
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:235) ~[PluginManagerCore.class:?]
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:43) ~[PluginManagerCore.class:?]
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:235) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:114) ~[StringUtil.class:?]
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:72) ~[StringUtil.class:?]
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:236) ~[PluginManagerCore.class:?]
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43) ~[PluginManagerCore.class:?]
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:70) ~[PluginManagerCore.class:?]
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:157) ~[ApplicationProperties.class:?]
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:122) ~[ApplicationProperties.class:?]
	at consulo.csharp.lang.psi.impl.source.CSharpUsingNamespaceStatementImpl.resolve(CSharpUsingNamespaceStatementImpl.java:80) ~[?:?]
	at consulo.csharp.lang.psi.impl.resolve.CSharpUsingNamespaceOrTypeResolveContext$1.compute(CSharpUsingNamespaceOrTypeResolveContext.java:58) ~[?:?]
	at consulo.csharp.lang.psi.impl.resolve.CSharpUsingNamespaceOrTypeResolveContext$1.compute(CSharpUsingNamespaceOrTypeResolveContext.java:47) ~[?:?]
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:40) ~[StringUtil.class:?]
	at consulo.csharp.lang.psi.impl.resolve.CSharpUsingNamespaceOrTypeResolveContext.findByName(CSharpUsingNamespaceOrTypeResolveContext.java:115) ~[?:?]
	at consulo.csharp.lang.psi.resolve.MemberByNameSelector.doSelectElement(MemberByNameSelector.java:51) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.resolve.MemberResolveScopeProcessor.execute(MemberResolveScopeProcessor.java:104) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.resolve.util.CSharpResolveUtil.walkUsing(CSharpResolveUtil.java:179) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.processAnyMember(CSharpReferenceExpressionImplUtil.java:1020) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.resolve.handlers.TypeLikeKindProcessor.process(TypeLikeKindProcessor.java:42) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.collectResults(CSharpReferenceExpressionImplUtil.java:752) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:732) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.buildSelectorAndMultiResolve(CSharpReferenceExpressionImplUtil.java:676) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolveImpl(CSharpReferenceExpressionImplUtil.java:634) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolveImpl(CSharpStubReferenceExpressionImpl.java:142) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:83) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil$OurResolver.resolve(CSharpReferenceExpressionImplUtil.java:74) ~[?:?]
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:153) ~[PluginManagerCore.class:?]
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:181) ~[PluginManagerCore.class:?]
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:172) ~[PluginManagerCore.class:?]
	at consulo.csharp.lang.psi.impl.source.CSharpReferenceExpressionImplUtil.multiResolve(CSharpReferenceExpressionImplUtil.java:271) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:134) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.multiResolve(CSharpStubReferenceExpressionImpl.java:126) ~[?:?]
	at consulo.csharp.lang.psi.impl.source.CSharpStubReferenceExpressionImpl.resolve(CSharpStubReferenceExpressionImpl.java:158) ~[?:?]
	at consulo.csharp.ide.codeInsight.CSharpTargetElementUtilEx.modifyReferenceOrReferencedElement(CSharpTargetElementUtilEx.java:58) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at consulo.extensions.CompositeExtensionPointName$MyInvocationHandler.invokeMethod(CompositeExtensionPointName.java:122) ~[ApplicationProperties.class:?]
	at consulo.extensions.CompositeExtensionPointName$MyInvocationHandler.invoke(CompositeExtensionPointName.java:113) ~[ApplicationProperties.class:?]
	at com.sun.proxy.$Proxy111.modifyReferenceOrReferencedElement(Unknown Source) ~[?:?]
	at consulo.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:213) ~[FileBasedIndexImpl.class:?]
	at consulo.codeInsight.TargetElementUtil.findTargetElementImpl(TargetElementUtil.java:190) ~[FileBasedIndexImpl.class:?]
	at consulo.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:155) ~[FileBasedIndexImpl.class:?]
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90) ~[FileBasedIndexImpl.class:?]
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:60) ~[DaemonCodeAnalyzerEx.class:?]
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:425) ~[FileBasedIndexImpl.class:?]
	at consulo.application.impl.BaseApplication.tryRunReadAction(BaseApplication.java:550) ~[ApplicationStarter.class:?]
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418) ~[FileBasedIndexImpl.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63) ~[ApplicationStarter.class:?]
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:417) ~[FileBasedIndexImpl.class:?]
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:393) ~[FileBasedIndexImpl.class:?]
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:180) [ApplicationStarter.class:?]
	at consulo.application.impl.BaseApplication.executeByImpatientReader(BaseApplication.java:604) [ApplicationStarter.class:?]
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:391) [FileBasedIndexImpl.class:?]
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:164) [ApplicationStarter.class:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
[ 389382]  ERROR - stubs.StubProcessingHelperBase - Consulo 2021.4  Build #2882 
[ 389382]  ERROR - stubs.StubProcessingHelperBase - JDK: 11.0.9.1 
[ 389382]  ERROR - stubs.StubProcessingHelperBase - VM: OpenJDK 64-Bit Client VM 
[ 389382]  ERROR - stubs.StubProcessingHelperBase - Vendor: AdoptOpenJDK 
[ 389382]  ERROR - stubs.StubProcessingHelperBase - OS: Windows 10 
[ 389383]  ERROR - stubs.StubProcessingHelperBase - Last Action: CodeCompletion 
```

**Comment by VISTALL** [comment]
Hello. Can you invoke, File -> Invalidate Caches & Restart -> Invalidate & Restart. And test again

**Comment by Zeon8** [comment]
It finally worked. Thanks!
