### ISSUE TITLE
Plugin error after updating to the newest version of Consulo

### ISSUE THREAD

**Issue by 76200** [consulo/consulo-unity3d#77]
After running Consulo 1.0 #1335 @ OS X 10.11.4 I get following error:

`org.mustbe.consulo.csharp.lang.psi.impl.source.resolve.type.CSharpTypeRefByQName.<init>(Lcom/intellij/psi/PsiElement;Ljava/lang/String;)V: org.mustbe.consulo.csharp.lang.psi.impl.source.resolve.type.CSharpTypeRefByQName.<init>(Lcom/intellij/psi/PsiElement;Ljava/lang/String;)V
java.lang.NoSuchMethodError: org.mustbe.consulo.csharp.lang.psi.impl.source.resolve.type.CSharpTypeRefByQName.<init>(Lcom/intellij/psi/PsiElement;Ljava/lang/String;)V
    at org.mustbe.consulo.unity3d.csharp.codeInsight.inspection.UnityNewMonoBehaviourInspection$1.visitNewExpression(UnityNewMonoBehaviourInspection.java:55)
    at org.mustbe.consulo.csharp.lang.psi.impl.source.CSharpNewExpressionImpl.accept(CSharpNewExpressionImpl.java:64)
    at org.mustbe.consulo.csharp.lang.psi.impl.source.CSharpElementImpl.accept(CSharpElementImpl.java:57)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1123)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:289)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:286)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:239)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
`

I also can't put a breakpoint on the code.

**Comment by VISTALL** [comment]
You need update plugins .NET API + C# plugin

**Comment by 76200** [comment]
Yeah! It works now, thanks.

**Comment by VISTALL** [comment]
np
