### ISSUE TITLE
SerializeProperty hangs Unity and debuger

### ISSUE THREAD

**Issue by winxalex** [consulo/consulo-unity3d#90]
Open any SerializedProperty in Variables,Watch..... Collecting data... for ever

**Comment by VISTALL** [comment]
Hi. Currently i am busy with next version of Consulo. Can't check . Sorry

**Comment by winxalex** [comment]
It crash Unity now when I open drop down to inspect. I know u working on C2 I"ve found many bugs no time to send. UnityEditor console isn't bad but no point when I need to focus Unity every time to run the compiling. Maybe you can do it like some compile button or....just idea for C2

**Comment by VISTALL** [comment]
I am no idea about compilation. Need find this API inside UnityEditor. And test it

**Comment by VISTALL** [comment]
Can you provide code sample? 

Thanks

**Comment by winxalex** [comment]
file1: `class MyBehaviour:MonoBehaviour{ public int mile }` 
file2:
`[CustomEditor(typeof(MyBehaviour)]
class MyEditor:Editor{
OnEnable(){ SerializedProperty property=this.serializedObject.FindProperty("mile");

Debug.Log(property);//check property in Debugger => "Collecting data..." forever

}
}` BTW I've ton of bugs :dagger:

**Comment by VISTALL** [comment]
Thanks.

**Comment by VISTALL** [comment]
You can always report bugs. But with sample pls. Thanks

**Comment by VISTALL** [comment]
OnEnable() is event method for Editors? (like OnUpdate for MonoBehaviour). Looks like need support this

**Comment by winxalex** [comment]
also OnInspectorGUI where is used the most

**Comment by VISTALL** [comment]
Ok. I will search docs for this methods, and will add it.

![](http://klikr.org/a2a5fcf786d9478500a06ec4a802.png)

Strange - can't repeat. Can you say your Unity version? Used Unity 5.1.2f1

**Comment by winxalex** [comment]
5.5.0.b11

**Comment by VISTALL** [comment]
About ton bugs. You use C# 6 features ?

**Comment by VISTALL** [comment]
Tested with Unity 5.5. Maybe problem with your property type. It was **int**?
![](http://klikr.org/6f9c949c9a4ce66b87242d256b72.png)

**Comment by winxalex** [comment]
No I'm not using C# features. Consulo 1.0 # 1401

**Comment by VISTALL** [comment]
Now OnEnable now have marker (only consulo 2)

![](http://klikr.org/74f63f95715abb99724d6b3c83dc.png)

**Comment by winxalex** [comment]
<img width="1440" alt="screen shot 2016-11-28 at 2 44 28 pm" src="https://cloud.githubusercontent.com/assets/689092/20670518/7632f31a-b579-11e6-89cb-2d326ab85e9e.png">
<img width="1440" alt="screen shot 2016-11-28 at 2 44 41 pm" src="https://cloud.githubusercontent.com/assets/689092/20670517/763205ea-b579-11e6-8eb2-b38b4d9458fb.png">
Only why is to get out is to Force close Unity. I'm not using Consulo debugger for some time.

DO you want video if u not belive me?

**Comment by winxalex** [comment]
When I force close Unity, Consulo unhang and show this error
`connection is closed: connection is closed
mono.debugger.VMDisconnectedException: connection is closed
	at mono.debugger.TargetVM.send(TargetVM.java:338)
	at mono.debugger.VirtualMachineImpl.sendToTarget(VirtualMachineImpl.java:451)
	at mono.debugger.PacketStream.send(PacketStream.java:71)
	at mono.debugger.protocol.Type_GetMethods.enqueueCommand(Type_GetMethods.java:27)
	at mono.debugger.protocol.Type_GetMethods.process(Type_GetMethods.java:19)
	at mono.debugger.TypeMirror.methods(TypeMirror.java:184)
	at mono.debugger.TypeMirror.findMethodByName(TypeMirror.java:226)
	at consulo.dotnet.mono.debugger.proxy.MonoTypeProxy.findMethodByName(MonoTypeProxy.java:183)
	at consulo.dotnet.debugger.nodes.DotNetValuePresentation$2.visitStructValue(DotNetValuePresentation.java:200)
	at consulo.dotnet.mono.debugger.proxy.MonoStructValueProxy.accept(MonoStructValueProxy.java:92)
	at consulo.dotnet.debugger.nodes.DotNetValuePresentation.renderValue(DotNetValuePresentation.java:119)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValuePresentationUtil.computeValueText(XValuePresentationUtil.java:91)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.applyPresentation(XValueNodeImpl.java:109)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodePresentationConfigurator.doSetPresentation(XValueNodePresentationConfigurator.java:95)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodePresentationConfigurator.setPresentation(XValueNodePresentationConfigurator.java:59)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.setPresentation(XValueNodeImpl.java:98)
	at consulo.dotnet.debugger.nodes.DotNetAbstractVariableValueNode.computePresentation(DotNetAbstractVariableValueNode.java:300)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:73)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode$1.run(XValueContainerNode.java:98)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:83)
	at com.intellij.util.containers.TransferToEDTQueue$2.process(TransferToEDTQueue.java:80)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:406)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by VISTALL** [comment]
Consulo hung while debugger invoking - is another issue https://github.com/consulo/consulo-dotnet/issues/72


Looks like - need give time for it

**Comment by VISTALL** [comment]
working on **consulo hung**

**Comment by winxalex** [comment]
Try with `int[]` Array.

**Comment by VISTALL** [comment]
The same result. Not hanging

**Comment by VISTALL** [comment]
Closed since https://github.com/consulo/consulo-dotnet/issues/72 closed
